import ReadTextPattern, FrequentWordsWMismatch, WriteArrayToFile

#text = ReadTextPattern.ReadTextPattern('D:\Halynka\Coursera - BioInf Algor\dataset_9_7.txt')
Text = 'CACAGTAGGCGCCGGCACACACAGCCCCGGGCCCCGGGCCGCCCCGGGCCGGCGGCCGCCGGCGCCGGCACACCGGCACAGCCGTACCGGCACAGTAGTACCGGCCGGCCGGCACACCGGCACACCGGGTACACACCGGGGCGCACACACAGGCGGGCGCCGGGCCCCGGGCCGTACCGGGCCGCCGGCGGCCCACAGGCGCCGGCACAGTACCGGCACACACAGTAGCCCACACACAGGCGGGCGGTAGCCGGCGCACACACACACAGTAGGCGCACAGCCGCCCACACACACCGGCCGGCCGGCACAGGCGGGCGGGCGCACACACACCGGCACAGTAGTAGGCGGCCGGCGCACAGCC'
#print len(Genome)
#k = int(k)
#dist = int(dist)

res = FrequentWordsWMismatch.FrequentWordsWMismatch(text, 10, 2)
print res
#WriteArrayToFile.WriteArrayToFile(res, 'result2.txt')
